# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeocodingPlugin
                                 A QGIS plugin
 This plugin geocodes the addresses using TPL in-house geocoding API.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-28
        copyright            : (C) 2020 by Shehar Bano
        email                : shehar.bano@tplmaps.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeocodingPlugin class from file GeocodingPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geocoding_plugin import GeocodingPlugin
    return GeocodingPlugin(iface)
